#!/usr/bin/env bash
# Generate a PR body for the given branch.
#
# Usage: pr-body.sh <branch>
#
# Template discovery order (first match wins, case-insensitive for the first):
#   1. .github/pull_request_template.md  (case-insensitive glob)
#   2. .github/PULL_REQUEST_TEMPLATE.md
#   3. .github/PULL_REQUEST_TEMPLATE/*.md  (first file, sorted)
#   4. .claude/pr-template.md
#
# If a template is found it is emitted with light variable substitution.
# If none is found, emit a structured fallback: ## Summary, ## Test Plan, and
# a stack-navigation footer linking parent/child PR numbers from the stack graph.
#
# Output guarantees (enforced by post-processing):
#   - No T<digit> task tokens
#   - No decorative emoji
#   - No "Generated by" or changelog lines
#
# This script is the single source of PR formatting; both create and update
# paths call it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARED_LIB="$SCRIPT_DIR/../../../_lib/jsonl-append.sh"
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)

_usage() {
  cat >&2 <<'USAGE'
pr-body.sh — generate a PR body from a template or a structured fallback

Usage:
  pr-body.sh <branch>

Output: PR body text on stdout.  Used by stack-submit (create) and stack-restack
(update) so formatting is always consistent.
USAGE
  exit 1
}

case "${1:-}" in
  --help|-h) _usage ;;
esac

BRANCH="${1:-}"
[[ -n "$BRANCH" ]] || _usage

# --- Template discovery ---------------------------------------------------

_find_template() {
  # 1. Case-insensitive match for pull_request_template.md under .github/
  local f
  f=$(find "$REPO_ROOT/.github" -maxdepth 1 \
      -iname "pull_request_template.md" 2>/dev/null | head -1)
  [[ -n "$f" ]] && { echo "$f"; return 0; }

  # 2. Exact uppercase form (already covered by case-insensitive above on most
  #    filesystems, but the plan specifies this as a distinct step).
  f="$REPO_ROOT/.github/PULL_REQUEST_TEMPLATE.md"
  [[ -f "$f" ]] && { echo "$f"; return 0; }

  # 3. Any .md file under .github/PULL_REQUEST_TEMPLATE/ (sorted, first wins).
  f=$(find "$REPO_ROOT/.github/PULL_REQUEST_TEMPLATE" -maxdepth 1 \
      -name "*.md" 2>/dev/null | sort | head -1)
  [[ -n "$f" ]] && { echo "$f"; return 0; }

  # 4. Claude-local template.
  f="$REPO_ROOT/.claude/pr-template.md"
  [[ -f "$f" ]] && { echo "$f"; return 0; }

  return 1
}

# --- Noise stripping ------------------------------------------------------

# Applied to any output before printing.  Removes:
#   - Lines containing T<digit> task tokens (e.g. T1, T2)
#   - "generated by" / changelog / co-author lines (case-insensitive)
#   - Decorative emoji anywhere on a line (inline, not just emoji-only lines)
# The emoji pass needs perl -CSD so the pattern matches decoded codepoints, not
# raw UTF-8 bytes — without it the \x{...} ranges never match.
_strip_noise() {
  grep -Ev '(^|[^a-zA-Z])T[0-9]+([^a-zA-Z]|$)' \
  | grep -iEv 'generated by|changelog:|auto-generated|co-authored-by' \
  | perl -CSD -pe 's/[\x{1F300}-\x{1FAFF}\x{2600}-\x{27BF}\x{FE00}-\x{FE0F}]//g' \
  || true
}

# --- Stack navigation footer ---------------------------------------------

_stack_footer() {
  local parent parent_pr children_info
  parent=$("$SCRIPT_DIR/stack-graph.sh" get "$BRANCH" 2>/dev/null \
    | jq -re '.parent' 2>/dev/null) || parent=""
  parent_pr=""
  if [[ -n "$parent" ]]; then
    parent_pr=$("$SCRIPT_DIR/stack-graph.sh" get "$BRANCH" 2>/dev/null \
      | jq -r '.pr_number | if . == null then "" else "#\(.)" end' 2>/dev/null) || parent_pr=""
  fi

  # Find children: branches in the graph whose parent == BRANCH.
  children_info=""
  while IFS= read -r b; do
    [[ -z "$b" ]] && continue
    entry=$("$SCRIPT_DIR/stack-graph.sh" get "$b" 2>/dev/null) || continue
    p=$(printf '%s' "$entry" | jq -re '.parent' 2>/dev/null) || continue
    if [[ "$p" == "$BRANCH" ]]; then
      pr=$(printf '%s' "$entry" | jq -r '.pr_number | if . == null then "" else "#\(.)" end' 2>/dev/null) || pr=""
      if [[ -n "$pr" ]]; then
        children_info="${children_info}- Child: $b ($pr)"$'\n'
      else
        children_info="${children_info}- Child: $b"$'\n'
      fi
    fi
  done < <("$SCRIPT_DIR/stack-graph.sh" list 2>/dev/null || true)

  echo ""
  echo "---"
  echo "**Stack position**"
  if [[ -n "$parent" ]]; then
    if [[ -n "$parent_pr" ]]; then
      echo "- Parent: $parent ($parent_pr)"
    else
      echo "- Parent: $parent"
    fi
  fi
  if [[ -n "$children_info" ]]; then
    printf '%s' "$children_info"
  fi
}

# --- Summary from diff ---------------------------------------------------

_diff_summary() {
  local parent
  parent=$("$SCRIPT_DIR/stack-graph.sh" get "$BRANCH" 2>/dev/null \
    | jq -re '.parent' 2>/dev/null) || parent="HEAD~1"

  # Produce a concise list of changed files and a stat line.
  echo "_Changes in this branch (relative to $parent):_"
  echo ""
  git diff --stat "${parent}...${BRANCH}" 2>/dev/null | head -20 || true
  echo ""
  echo "_Commits:_"
  echo ""
  git log --oneline "${parent}..${BRANCH}" 2>/dev/null | head -20 || true
}

# --- Main ----------------------------------------------------------------

TEMPLATE=$(_find_template 2>/dev/null || true)

if [[ -n "$TEMPLATE" ]]; then
  # Emit the template with noise stripped.
  cat "$TEMPLATE" | _strip_noise
  _stack_footer
else
  # Structured fallback.
  echo "## Summary"
  echo ""
  _diff_summary
  echo ""
  echo "## Test Plan"
  echo ""
  echo "- [ ] "
  _stack_footer
fi | _strip_noise

# Log the op.
REPO_KEY=$("$SCRIPT_DIR/repo-key.sh" 2>/dev/null || echo "unknown")
OPS_LOG="${CLAUDE_PLUGIN_DATA:-$(pwd)/.claude}/stack-flow/${REPO_KEY}/ops.jsonl"
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
SOURCE=$([[ -n "$TEMPLATE" ]] && echo "template:$TEMPLATE" || echo "fallback")
bash "$SHARED_LIB" "$OPS_LOG" \
  "$(jq -nc --arg op "pr-body" --arg branch "$BRANCH" \
      --arg source "$SOURCE" --arg ts "$TS" \
      '{op:$op,branch:$branch,source:$source,ts:$ts}')"
