#!/usr/bin/env bash
# Contract criterion 4: PR body uses a template when present and a clean fallback
# when absent, with zero noise.

set -euo pipefail

TESTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$TESTS_DIR/../_lib"
PR_BODY="$LIB_DIR/pr-body.sh"

PASS_COUNT=0
FAIL_COUNT=0

_pass() { echo "  PASS: $1"; PASS_COUNT=$((PASS_COUNT+1)); }
_fail() { echo "  FAIL: $1"; FAIL_COUNT=$((FAIL_COUNT+1)); }

# Setup: tmp dirs.
TMP=$(mktemp -d)
export CLAUDE_PLUGIN_DATA="$TMP/state"
mkdir -p "$CLAUDE_PLUGIN_DATA"

# Build a fake `gh` shim (pr-body.sh calls stack-graph which doesn't need gh,
# but just in case avoid network calls).
GH_BIN="$TMP/bin"
mkdir -p "$GH_BIN"
cat > "$GH_BIN/gh" <<'GHEOF'
#!/usr/bin/env bash
echo '{}' ; exit 0
GHEOF
chmod +x "$GH_BIN/gh"
export PATH="$GH_BIN:$PATH"

trap 'rm -rf "$TMP" "${FIXTURE_REPO:-}"' EXIT

# Build fixture repo.
FIXTURE_REPO=$(CLAUDE_PLUGIN_DATA="$TMP/state" bash "$TESTS_DIR/mkfixture.sh")

echo "--- test-pr-body.sh ---"

# ----- Path A: template present -----
mkdir -p "$FIXTURE_REPO/.github"
# The template carries deliberate noise so the no-noise assertion below actually
# exercises _strip_noise: an inline-emoji line, a T<n> task token, and a
# "Generated by" line. If the filter regresses, the body keeps this noise.
cat > "$FIXTURE_REPO/.github/pull_request_template.md" <<'TMPL'
## Summary

This change ships the feature ✨ and a robot 🤖 inline.
Implements T3 from the tracker.
Generated by release-bot

## Test Plan

How was this tested?
TMPL

# Sanity: the source template must actually contain noise, else the no-noise
# assertion is tautological (would pass even with the filter removed).
if /usr/bin/grep -qE 'T[0-9]+|Generated by|🤖|✨' "$FIXTURE_REPO/.github/pull_request_template.md"; then
  _pass "template path: source template contains noise (filter is exercised)"
else
  _fail "template path: source template has no noise — no-noise assertion would be tautological"
fi

BODY_A=$(cd "$FIXTURE_REPO" && bash "$PR_BODY" feat-b 2>/dev/null) || {
  _fail "pr-body.sh (template path) exited non-zero"
  echo "test-pr-body.sh: 0 passed, $FAIL_COUNT failed"
  exit 1
}

if printf '%s' "$BODY_A" | grep -q "## Summary"; then
  _pass "template path: body contains ## Summary"
else
  _fail "template path: body missing ## Summary; body: $BODY_A"
fi

# Noise check for template path.
if ! printf '%s' "$BODY_A" | /usr/bin/grep -qE 'T[0-9]+|Generated by|🤖|✨'; then
  _pass "template path: no noise (T<n>, Generated by, emoji)"
else
  _fail "template path: body contains noise; body: $BODY_A"
fi

# ----- Path B: no template (fallback) -----
rm -f "$FIXTURE_REPO/.github/pull_request_template.md"
rmdir "$FIXTURE_REPO/.github" 2>/dev/null || true

# Add a commit whose subject carries noise so the fallback body (which includes
# the commit log) actually exercises _strip_noise. Without this the no-noise
# assertion is tautological — clean fixture commits can never leak noise.
( cd "$FIXTURE_REPO" && git checkout -q feat-b \
  && git commit -q --allow-empty -m "feat: extra work T9 done generated by bot 🤖" )
RAW_LOG=$(cd "$FIXTURE_REPO" && git log --oneline feat-a..feat-b 2>/dev/null || true)
if printf '%s' "$RAW_LOG" | /usr/bin/grep -qE 'T[0-9]+|generated by|🤖'; then
  _pass "fallback path: source commit log contains noise (filter is exercised)"
else
  _fail "fallback path: source log has no noise — no-noise assertion would be tautological"
fi

BODY_B=$(cd "$FIXTURE_REPO" && bash "$PR_BODY" feat-b 2>/dev/null) || {
  _fail "pr-body.sh (fallback path) exited non-zero"
  echo "test-pr-body.sh: 0 passed, $FAIL_COUNT failed"
  exit 1
}

if printf '%s' "$BODY_B" | grep -q "## Summary"; then
  _pass "fallback path: body contains ## Summary"
else
  _fail "fallback path: body missing ## Summary; body: $BODY_B"
fi

if printf '%s' "$BODY_B" | grep -q "## Test Plan"; then
  _pass "fallback path: body contains ## Test Plan"
else
  _fail "fallback path: body missing ## Test Plan; body: $BODY_B"
fi

if printf '%s' "$BODY_B" | grep -q "Stack position"; then
  _pass "fallback path: body contains stack-navigation footer"
else
  _fail "fallback path: body missing stack-navigation footer; body: $BODY_B"
fi

# Noise check for fallback path.
if ! printf '%s' "$BODY_B" | /usr/bin/grep -qE 'T[0-9]+|Generated by|🤖|✨'; then
  _pass "fallback path: no noise (T<n>, Generated by, emoji)"
else
  _fail "fallback path: body contains noise; body: $BODY_B"
fi

# Summary
echo ""
echo "test-pr-body.sh: $PASS_COUNT passed, $FAIL_COUNT failed"
[[ "$FAIL_COUNT" -eq 0 ]]
